In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/Users/vero/Documents/Web_Analytics_&_BI/Assignments/Final_exam/covid_activity.csv')
data.head(5)

/Users/vero/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,PEOPLE_POSITIVE_CASES_COUNT,COUNTY_NAME,PROVINCE_STATE_NAME,REPORT_DATE,CONTINENT_NAME,DATA_SOURCE_NAME,PEOPLE_DEATH_NEW_COUNT,COUNTY_FIPS_NUMBER,COUNTRY_ALPHA_3_CODE,COUNTRY_SHORT_NAME,COUNTRY_ALPHA_2_CODE,PEOPLE_POSITIVE_NEW_CASES_COUNT,PEOPLE_DEATH_COUNT
0,2537,NaN,NaN,2021-01-10,Africa,JHU CSSE Global Timeseries,0,NaN,TCD,Chad,TD,27,107
1,266,NaN,Nunavut,2021-01-10,America,JHU CSSE Global Timeseries,0,NaN,CAN,Canada,CA,0,1
2,3072349,NaN,NaN,2021-01-10,Europe,JHU CSSE Global Timeseries,563,NaN,GBR,United Kingdom,GB,54940,81431
3,230578,NaN,NaN,2021-01-10,Asia,JHU CSSE Global Timeseries,6,NaN,ARE,United Arab Emirates,AE,2876,708
4,196,NaN,NaN,2021-01-10,America,JHU CSSE Global Timeseries,0,NaN,BES,"Bonaire, Sint Eustatius and Saba",BQ,0,3

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1580624 entries, 0 to 1580623
Data columns (total 13 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   PEOPLE_POSITIVE_CASES_COUNT      1580624 non-null  int64
 1   COUNTY_NAME                      1460204 non-null  object
 2   PROVINCE_STATE_NAME              1485180 non-null  object
 3   REPORT_DATE                      1580624 non-null  object
 4   CONTINENT_NAME                   1579286 non-null  object
 5   DATA_SOURCE_NAME                 1580624 non-null  object
 6   PEOPLE_DEATH_NEW_COUNT           1580624 non-null  int64
 7   COUNTY_FIPS_NUMBER               1435228 non-null  float64
 8   COUNTRY_ALPHA_3_CODE             1579286 non-null  object
 9   COUNTRY_SHORT_NAME               1580624 non-null  object
 10  COUNTRY_ALPHA_2_CODE             1578840 non-null  object
 11  PEOPLE_POSITIVE_NEW_CASES_COUNT  1580624 non-null  int64
 12  PEOPLE_DEATH_COUNT               1580624 non-null  int64
dtypes: float64(1), int64(4), object(8)
memory usage: 156.8+ MB